class Personnage:
    def __init__(self, nom:str, points_de_vie:int, force:int):
        self.nom = nom
        self.points_de_vie = points_de_vie
        self.force = force
    
    def attaquer(self, other_char):
        degats = 1.5 * self.force
        other_char.points_de_vie -= degats
        other_char.points_de_vie = round(other_char.points_de_vie,3)
        print(f"{other_char.nom} a perdu {degats} PV, il leurs reste {other_char.points_de_vie} PV.")

class Guerrier(Personnage):
    def __init__(self, nom, points_de_vie, force):
        super().__init__(nom, points_de_vie, force)
        self.force *= 1.25

class Mage(Personnage):
    def __init__(self, nom, points_de_vie, force, spell_power:int):
        super().__init__(nom, points_de_vie, force)
        self.spell_power = spell_power
    

    
    def lancer_un_sort(self, other_char):
        # spell and art generated by Chat-GPT
        spell = """
        Ô puissance qui dort dans l'éther,
        Réveille-toi, embrase la terre !
        Que l'éclair frappe en un instant,
        Et consume tout en un torrent :
        Fulmen Ignis !
        """
        art = """
    (   )
   (     )
  (       )
   \\  |  /
    \\ | /
     \\|/
     /|\\
    / | \\
"""
        print(spell)
        print(art)
        degats = 2 * self.spell_power
        other_char.points_de_vie -= degats
        other_char.points_de_vie = round(other_char.points_de_vie,3)
        self.points_de_vie *= 0.85
        print(f"{other_char.nom} a perdu {degats} PV, il leurs reste {other_char.points_de_vie} PV.")
    
    def attaquer(self, other_char):
        self.lancer_un_sort(other_char)


class Combat():
    def __init__(self, first_char:Personnage, second_char:Personnage):
        self.first_char = first_char
        self.second_char = second_char
        
    def lancer_combat(self):
        tour = 1
        for char in [self.first_char, self.second_char]:
            print(f"{char.nom} a {char.points_de_vie} PV.")
        while self.first_char.points_de_vie > 0 and self.second_char.points_de_vie > 0:
            print(f"\nTour {tour}: \n")
            self.first_char.attaquer(self.second_char)
            self.second_char.attaquer(self.first_char)
            tour += 1
        
            
        for char in [self.first_char, self.second_char]:
            if char.points_de_vie > 0:
                winner = char.nom
                print(f"Félicitation {winner}, vous avez gagné !")
                break
            else:
                print("Personne ne gagne, égalité.")
                break


mage = Mage("Merlin", 260, 30, 90)
warrior = Guerrier("Sun Wukong", 320, 60)

my_fight = Combat(mage,warrior)
my_fight.lancer_combat()
